In [19]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x, y):
    """구현해야 하는 부분"""
    ata_inv = np.linalg.inv(np.matmul(np.transpose(x),x))
    atb = np.matmul(np.transpose(x),y)
    beta_hat = np.matmul(ata_inv,atb)
    return beta_hat

In [20]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [21]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [22]:
y

array([1, 3, 7])

In [23]:
estimate_beta(x,y)

array([0.25, 0.25, 0.75])